<? $this->headTitle(
    $this->translate('HR')) ?>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <legend>
                <span class="glyphicon glyphicon-user"></span>
                <a href="<?= $this->url('backHR') ?>">
                    <?= $this->translate('HR') ?>
                </a>
            </legend>
        </div>
    </div>
    <div class="row">
    </div>
</div>
