<?

return [
    'guest' => [
        'home',
        'backAuth',
        'backAuth/process',
        'news',
        'products',
        'documentation',
        'community',
        'support',
        'about',
    ],
    'user' => [
        'account',
        // 'account/orders',
        // 'account/settings',
        // 'store/shoppingCart',
    ],
    'client' => [
        'back',
        'backStore',
        'backStoreEcommerce',
        'backStoreReport',
        'backStoreCatalog',
        'backStoreCatalogProduct',
        'backStoreOrders',
        'backStoreShippment',
        'backStoreMarketplace',
        'backSettings',
        'backSettingsCurrency',
        'backMonitoring',
        'backCRM',
        'backCRMManagers',
        'backCRMClientsEmployees',
        'backCRMClients',
        'backFinance',
        'backFinanceReport',
        'backFinanceAccounts',
        'backFinanceCosts',
        'backFinanceProfit',
        'backFinanceIncome',
        'backProduction',
        'backProductionResources',
        'backHR',
        'backHREmployees',
        'backHRSecurityCredentials',
        'backHRDepartments',
        'backHRPositions',
        'backDocumentation',
        'backAccount',
        'backAccountSettings',
        'backCMS',
        'backCMSNews',
    ],
    'admin' => [
    ],
    'dev' => [
    ],
];
