<? if ($this->pageCount) : ?> 
    <ul class="pagination">
        <li <?= (!isset($previous)) ? 'class="disabled"' : '' ?>>
            <a href="<?= $this->url(
                    'backStoreOrders', 
                    [
                        'page' => isset($first) ? $first : null,
                        'order_by' => $this->order_by ? $this->order_by : null, 
                        'order' => $this->order ? $this->order : null,
                        'id_status' => $this->currentStatus ? $this->currentStatus : null, 
                    ]) ?>">
                &laquo;
            </a>
        </li>
        <li <?= (!isset($previous)) ? 'class="disabled"' : '' ?>>
            <a href="<?= $this->url(
                    'backStoreOrders', 
                    [
                        'page' => isset($previous) ? $previous : null,
                        'order_by' => $this->order_by ? $this->order_by : null, 
                        'order' => $this->order ? $this->order : null,
                        'id_status' => $this->currentStatus ? $this->currentStatus : null, 
                    ]) ?>">
                &lsaquo;
            </a>
        </li>

        <? foreach ($this->pagesInRange as $page) : ?>
            <li <?= ($page == $this->current) ? 'class="active"' : '' ?>>
                <a href="<?= $this->url(
                        'backStoreOrders', 
                        [
                            'page' => isset($page) ? $page : null,
                            'order_by' => $this->order_by ? $this->order_by : null, 
                            'order' => $this->order ? $this->order : null,
                            'id_status' => $this->currentStatus ? $this->currentStatus : null, 
                        ]) ?>">
                    <?= $page ?>
                </a>
            </li>
        <? endforeach ?>

        <li <?= (!isset($next)) ? 'class="disabled"' : '' ?>>
            <a href="<?= $this->url(
                    'backStoreOrders', 
                    [
                        'page' => isset($next) ? $next : null,
                        'order_by' => $this->order_by ? $this->order_by : null, 
                        'order' => $this->order ? $this->order : null,
                        'id_status' => $this->currentStatus ? $this->currentStatus : null, 
                    ]) ?>">
                &rsaquo;
            </a>
        </li>
        <li <?= (!isset($next)) ? 'class="disabled"' : '' ?>>
            <a href="<?= $this->url(
                    'backStoreOrders',
                    [
                        'page' => isset($last) ? $last : null,
                        'order_by' => $this->order_by ? $this->order_by : null, 
                        'order' => $this->order ? $this->order : null,
                        'id_status' => $this->currentStatus ? $this->currentStatus : null, 
                    ]) ?>">
                &raquo;
            </a>
        </li>
    </ul>
<? endif ?>
