<? $this->headTitle(
	$this->translate('Edit Password') . ' | ' .
    $this->translate('Edit') . ' | ' .
    $this->translate('Employees') . ' | ' .
    $this->translate('HR')) ?>

<? $url = $this->url(
    $this->url,
    [
        'action' => 'password',
        'id' => $this->item->id,
    ]
);
$this->form->setAttribute('action', $url);

$this->form->get('submit')->setAttribute(
    'value',
    $this->translate('Change Password')
);
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare() ?>

<div class="row">
    <legend>
        <span class="glyphicon glyphicon-shopping-cart"></span>
        <a href="<?= $this->translate('backHR') ?>">
            <?= $this->translate('HR') ?>
        </a>
        /
        <a href="<?= $this->url($this->url) ?>">
            <?= $this->translate('Employees') ?>
        </a>
        /
        <a href="<?= $this->url(
                $this->url,
                [
                    'action' => 'view',
                    'id' => $this->item->id,
                ]) ?>">
            <?= $this->item->first_name ?>
            <?= $this->item->last_name ?>
        </a>
        /
        <a href="<?= $this->url(
                $this->url,
                [
                    'action' => 'edit',
                    'id' => $this->item->id,
                ]) ?>">
            <?= $this->translate('Edit') ?>
        </a>
        /
        <a href="">
            <?= $this->translate('Change Password') ?>
        </a>
    </legend>
</div>

<div class="row">
    <?= $this->form()->openTag($this->form) ?>
        <div class="form-group">
            <div class="col-md-12">
                <a class="btn btn-default" href="<?= $this->url($this->url,
                [
                	'action' => 'edit',
                    'id' => $this->item->id,
                ]) ?>">
                    <?= $this->translate('Back') ?>
                </a>
                <?= $this->formInput(
                    $this->form->get('submit')
                        ->setAttribute('class', 'btn btn-success')
                        ->setValue($this->translate('Save'))) ?>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <label class="col-md-2 control-label">
                * <?= $this->translate('Current password') ?>:
            </label>
            <div class="col-md-3">
                <?= $this->formInput(
                    $this->form->get('password_current')
                        ->setAttribute('class', 'form-control input-md')) ?>

                <? if ($this->form->get('password_current')->getMessages()) : ?>
                    <span class="form-error">
                        <? foreach ($this->form->get('password_current')->getMessages() as $message) : ?>
                            <?= $message ?>
                        <? endforeach ?>
                    </span>
                <? endif ?>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <label class="col-md-2 control-label">
                * <?= $this->translate('New password') ?>:
            </label>
            <div class="col-md-3">
                <?= $this->formInput($this->form->get('password')->setAttribute('class', 'form-control input-md')) ?>
                <? if ($this->form->get('password')->getMessages()) : ?>
                    <span class="form-error">
                        <? foreach ($this->form->get('password')->getMessages() as $message) : ?>
                            <?= $message ?>
                        <? endforeach ?>
                    </span>
                <? endif ?>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <label class="col-md-2 control-label">
                * <?= $this->translate('Repeat password') ?>:
            </label>
            <div class="col-md-3">
                <?= $this->formInput(
                        $this->form->get('password_check')
                            ->setAttribute('class', 'form-control input-md')) ?>
                            
                <? if ($this->form->get('password_check')->getMessages()) : ?>
                    <span class="form-error">
                        <? foreach ($this->form->get('password_check')->getMessages() as $message) : ?>
                            <?= $message ?>
                            <br>
                        <? endforeach ?>
                    </span>
                <? endif ?>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <label class="col-md-2 control-label">
                <?= $this->translate('Last changes') ?>:
            </label>
            <div class="col-md-10">
                <span class="form-error control-label pull-left">
                    <?= $this->item->update ?>
                </span>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <label class="col-md-2 control-label">
                <?= $this->translate('Creation time') ?>:
            </label>
            <div class="col-md-10">
                <span class="form-error control-label pull-left">
                    <?= $this->item->created ?>
                </span>
            </div>
        </div>
    <?= $this->form()->closeTag() ?>
</div>
