<?= $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?= $this->headTitle($this->systemTitle)
            ->setSeparator(' | ')
            ->setAutoEscape(false) ?>
        
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>
        
        <?= $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/assets/back/img/redone-icon.ico'])
            ->prependStylesheet($this->basePath() . '/assets/back/css/xcharts.min.css')
            ->prependStylesheet($this->basePath() . '/assets/back/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/assets/back/font-awesome/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/assets/back/css/plugins/morris/morris-0.4.3.min.css')
            ->prependStylesheet($this->basePath() . '/assets/back/css/plugins/timeline/timeline.css')
            ->prependStylesheet($this->basePath() . '/assets/back/css/bootstrap3-wysiwyg5/bootstrap3-wysiwyg5.css')
            ->prependStylesheet($this->basePath() .
                    '/assets/back/js/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css')
            ->prependStylesheet($this->basePath() . '/assets/back/css/bootstrap-switch/bootstrap-switch.css')
            ->prependStylesheet($this->basePath() . '/assets/back/css/default.css') ?>
        <script src="/assets/back/js/jquery-2.1.1.min.js"></script>
        <script src="/assets/back/ckeditor/ckeditor.js"></script>
        <script src="/assets/back/js/xcharts.min.js"></script>
        <script src="/assets/back/js/d3.min.js"></script>
        <script type="text/javascript">
            translate = {
                yes: '<?= $this->translate('Yes') ?>',
                no: '<?= $this->translate('No') ?>'
            }
        </script>
    </head>
    <body>
        <nav class="top-navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                            
                    </button>
                    <a class="top-navbar-brand bold" href="<?= $this->url('back') ?>">
                        <?= $this->layout()->systemTitle ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav top-navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-globe"></span>
                                <?= $this->translate($this->layout()->locale_title) ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="/back/en">
                                        <? if ($this->layout()->locale == 'en') echo '<strong>' ?>
                                            <?= $this->translate('English') ?>
                                        <? if ($this->layout()->locale == 'en') echo '</strong>' ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="/back/ua">
                                        <? if ($this->layout()->locale == 'ua') echo '<strong>' ?>
                                            <?= $this->translate('Ukraine') ?>
                                        <? if ($this->layout()->locale == 'ua') echo '</strong>' ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="/back/ru">
                                        <? if ($this->layout()->locale == 'ru') echo '<strong>' ?>
                                            <?= $this->translate('Russian') ?>
                                        <? if ($this->layout()->locale == 'ru') echo '</strong>' ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-random"></span>
                                <?= $this->translate('System') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="<?= $this->url('home') ?>">
                                        <span class="glyphicon glyphicon-home"></span>
                                        <?= $this->translate('Back to Site') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('backAuth/process', ['action'=>'logout']) ?>">
                                        <span class="glyphicon glyphicon-remove"></span>
                                        <?= $this->translate('Log out') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="navbar navbar-default navbar-static-top navabar-module"
             role="navigation" style="z-index: 999">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <?
                    $r = $_SERVER["REQUEST_URI"];
                    $pages = [
                        'hr',
                    ];
                    $route = '/';
                    for ($i=0; $i<count($pages); $i++)
                        if (strpos($r, $pages[$i]))
                            $route = $pages[$i] ?>
                    <ul class="nav navbar-nav" style="padding-left: 15px;">
                        <li <? if ($route == '/') echo 'class="active"' ?>>
                            <a href="<?= $this->url('back') ?>">
                                <span class="glyphicon glyphicon-off"></span>
                                <?= $this->translate('Dashboard') ?>
                            </a>
                        </li>
                        <li <? if ($route == 'hr') echo 'class="active"' ?> class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span>
                                <?= $this->translate('HR') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="<?= $this->url('backHREmployees') ?>">
                                        <?= $this->translate('Employees') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <?= $this->content ?>
            <br>
        </div>
        <hr>
        <div class="container">
            <div class="row">
                <p class="copyright text-muted pull-left">
                    <span class="help-block">
                        © <?= date('Y') ?>
                        <a target="_blank" href="<?= $this->url('back') ?>">Red</a>.
                        <?= $this->translate('All rights reserved.') ?>
                    </span>
                </p>
            </div>
        </div>
        <?= $this->headScript()
            ->appendFile($this->basePath() . '/assets/back/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/assets/back/js/moment/moment.js')
            ->appendFile($this->basePath() .
                    '/assets/back/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js')
            ->appendFile($this->basePath() . '/assets/back/js/bootstrap-switch/bootstrap-switch.js')
            ->appendFile($this->basePath() . '/assets/back/js/default.js') ?>

        <script src="/assets/back/js/bootstrap-datetimepicker/js/locale/ru.js"></script>
        <script src="/assets/back/js/bootstrap-datetimepicker/js/locale/ua.js"></script>

        <!--        <script src="/assets/back/ckeditor/ckeditor.js"></script>-->

        <!-- Page-Level Plugin Scripts - Dashboard -->
<!--        <script src="/assets/back/js/plugins/morris/raphael-2.1.0.min.js"></script>-->
<!--        <script src="/assets/back/js/plugins/morris/morris.js"></script>-->

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="/assets/back/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="/assets/back/js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </body>
</html>
