<? $this->headTitle($this->translate('Welcome')) ?>

<?
$form = $this->form;
$form->setAttribute('action', $this->url(
    'backAuth/process',
    ['action' => 'authenticate']
));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="row">
    <? if ($this->messages) : ?>
        <? foreach ($this->messages as $message) : ?>
            <div class="panel-body">
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?= $this->translate($message) ?>
                </div>
            </div>
        <? endforeach ?>
    <? endif ?>        
    <div class="col-md-6 col-md-offset-4">
        <span class="back-auth-logo">
            Red Application
        </span>
    </div>
    <div class="col-md-6 col-md-offset-3">
        <hr>
        <div>
            <?= $this->form()->openTag($form) ?>
                <div class="form-group">
                    <label class="col-md-4 control-label">
                        <?= $this->translate('Email') ?>:
                    </label>
                    <div class="col-md-7">
                        <?= $this->formInput(
                            $form->get('email')
                                ->setAttribute('class', 'form-control input-md')
                        ) ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">
                        <?= $this->translate('Password') ?>:
                    </label>
                    <div class="col-md-7">
                        <?= $this->formInput(
                            $form->get('password')
                                ->setAttribute('class', 'form-control input-md')
                        ) ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label"></label>
                    <div class="col-md-4">
                        <div class="checkbox">
                            <?= $this->formRow($form->get('checkbox')) ?>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label"></label>
                    <div class="col-md-4">
                        <?= $this->formInput(
                            $form->get('submit')
                                ->setAttribute('class', 'btn btn-default')
                                ->setValue($this->translate('Log in'))
                        ) ?>
                    </div>
                </div>
            <?= $this->form()->closeTag() ?>
        </div>
        <hr>
    </div>
    <div class="col-md-6 col-md-offset-5">
        <a class="red-ink" href="<?= $this->url('home') ?>">
            <?= $this->translate('Back to site') ?>
        </a>
    </div>
</div>
